Completed tasks using JavaScript (5 tasks)
SlobodianykOleksandra/aqa-advanced pull request #2
Opened 2023-10-11 20:07 UTC by SlobodianykOleksandra

Homework number 2

2023-10-11 20:38 UTC, SlobodianykOleksandra commented on .idea/workspace.xml
delete this file

2023-10-11 21:36 UTC, sttaran requested changes

2023-10-11 21:36 UTC, sttaran commented on js_basics/Task1.js
> +let catWeight = 6
use `const` for all variables, you don't change them

2023-10-11 21:36 UTC, sttaran commented on js_basics/Task2.js
> +let dogWeight = 28
use `const` for all variables, you don't change them

2023-10-11 21:36 UTC, sttaran commented on js_basics/Task3.js
> +let helloText = 'Main characters of story are '+boyName+' and '+girlName
use `const` for all variables, you don't change them

2023-10-11 21:36 UTC, sttaran commented on js_basics/Task4.js
> +let heroAge = 25
use `const` for all variables, you don't change them

2023-10-11 21:36 UTC, sttaran commented on js_basics/Task5.js
> +let radius = 8
use `const` for all variables, you don't change them

2023-10-12 20:28 UTC, sttaran approved these changes

2023-10-15 14:57 UTC, merged